import { NextResponse } from "next/server";
import { getAdminAllowedEventIds, requirePermission } from "@/features/auth/auth.service";
import { getFinanceReport } from "@/features/finance/finance-report.service";
import { formatCurrency } from "@/lib/format";

export const dynamic = "force-dynamic";
type Report = Awaited<ReturnType<typeof getFinanceReport>>;
type Row = Report["byEvent"][number];
const W=842,H=884, green="0 .31 .22 rg", green2="0 .42 .29 rg", bright=".08 .72 .45 rg", pale=".89 .97 .93 rg", ink=".04 .08 .12 rg", muted=".34 .40 .48 rg", line=".84 .89 .87 RG", white="1 1 1 rg";

function literal(value:unknown){const bytes=Buffer.from(String(value??"").replace(/[–—]/g,"-"),"latin1");let out="";for(const b of bytes){if(b===40||b===41||b===92)out+=`\\${String.fromCharCode(b)}`;else if(b<32||b>126)out+=`\\${b.toString(8).padStart(3,"0")}`;else out+=String.fromCharCode(b)}return out}
const rect=(x:number,y:number,w:number,h:number,c:string)=>`${c}\n${x} ${y} ${w} ${h} re f`;
const stroke=(x:number,y:number,w:number,h:number,c=line,l=.6)=>`${c}\n${l} w\n${x} ${y} ${w} ${h} re S`;
const rule=(x:number,y:number,x2:number,y2:number,c=line,l=.6)=>`${c}\n${l} w\n${x} ${y} m ${x2} ${y2} l S`;
function txt(x:number,y:number,v:unknown,s=9,b=false,c=ink,max=80){return `${c}\nBT /${b?"F2":"F1"} ${s} Tf ${x} ${y} Td (${literal(v).slice(0,max*4)}) Tj ET`}
function circle(cx:number,cy:number,r:number,c:string){const k=.5522848*r;return `${c}\n${cx+r} ${cy} m ${cx+r} ${cy+k} ${cx+k} ${cy+r} ${cx} ${cy+r} c ${cx-k} ${cy+r} ${cx-r} ${cy+k} ${cx-r} ${cy} c ${cx-r} ${cy-k} ${cx-k} ${cy-r} ${cx} ${cy-r} c ${cx+k} ${cy-r} ${cx+r} ${cy-k} ${cx+r} ${cy} c f`}
function wedge(cx:number,cy:number,r:number,start:number,end:number,c:string){const pts=[];for(let a=start;a<=end+.001;a+=Math.max((end-start)/32,.05))pts.push([cx+r*Math.cos(a),cy+r*Math.sin(a)]);pts.push([cx+r*Math.cos(end),cy+r*Math.sin(end)]);return `${c}\n${cx} ${cy} m ${pts.map(p=>`${p[0].toFixed(2)} ${p[1].toFixed(2)} l`).join(" ")} h f`}
function ring(cx:number,cy:number,r:number,color="0 .42 .29 RG",width=1.7){const k=.5522848*r;return `${color}\n${width} w\n${cx+r} ${cy} m ${cx+r} ${cy+k} ${cx+k} ${cy+r} ${cx} ${cy+r} c ${cx-k} ${cy+r} ${cx-r} ${cy+k} ${cx-r} ${cy} c ${cx-r} ${cy-k} ${cx-k} ${cy-r} ${cx} ${cy-r} c ${cx+k} ${cy-r} ${cx+r} ${cy-k} ${cx+r} ${cy} c S`}
function vectorIcon(cmd:string[],x:number,y:number,kind:"cart"|"ticket"|"coins"|"percent"|"card",scale=1,color="0 .42 .29 RG"){
  const p=(value:number)=>Number((value*scale).toFixed(2));
  if(kind==="cart"){cmd.push(`${color}\n${p(1.8)} w\n${x-p(10)} ${y+p(8)} m ${x-p(7)} ${y+p(8)} l ${x-p(4)} ${y-p(4)} l ${x+p(8)} ${y-p(4)} l ${x+p(10)} ${y+p(4)} l ${x-p(5)} ${y+p(4)} l S`,ring(x-p(2),y-p(9),p(1.6),color,p(1.4)),ring(x+p(7),y-p(9),p(1.6),color,p(1.4)))}
  if(kind==="ticket"){cmd.push(`${color}\n${p(1.8)} w\n${x-p(11)} ${y-p(7)} m ${x+p(11)} ${y-p(7)} l ${x+p(11)} ${y-p(2)} l ${x+p(8)} ${y} ${x+p(11)} ${y+p(2)} ${x+p(11)} ${y+p(7)} c ${x-p(11)} ${y+p(7)} l ${x-p(11)} ${y+p(2)} l ${x-p(8)} ${y} ${x-p(11)} ${y-p(2)} ${x-p(11)} ${y-p(7)} c S`,rule(x+p(3),y-p(6),x+p(3),y+p(6),color,p(1)))}
  if(kind==="coins"){cmd.push(ring(x,y+p(6),p(9),color,p(1.7)),`${color}\n${p(1.7)} w\n${x-p(9)} ${y+p(6)} m ${x-p(9)} ${y} l ${x-p(8)} ${y-p(3)} ${x} ${y-p(5)} ${x+p(8)} ${y-p(3)} c ${x+p(9)} ${y} l ${x+p(9)} ${y+p(6)} l S ${x-p(9)} ${y} m ${x-p(9)} ${y-p(6)} l ${x-p(8)} ${y-p(9)} ${x} ${y-p(11)} ${x+p(8)} ${y-p(9)} c ${x+p(9)} ${y-p(6)} l ${x+p(9)} ${y} l S`)}
  if(kind==="percent"){cmd.push(ring(x-p(6),y+p(6),p(2.5),color,p(1.6)),ring(x+p(6),y-p(6),p(2.5),color,p(1.6)),rule(x-p(8),y-p(9),x+p(8),y+p(9),color,p(1.8)))}
  if(kind==="card"){cmd.push(stroke(x-p(11),y-p(7),p(22),p(14),color,p(1.7)),rule(x-p(10),y+p(2),x+p(10),y+p(2),color,p(1.7)),rule(x-p(7),y-p(3),x-p(2),y-p(3),color,p(1.5)))}
}
function datePt(v:string){const [y,m,d]=v.split("-");return y&&m&&d?`${d}/${m}/${y}`:v}
function issued(d:Date){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(d)}
function filterLabel(report:Report){const event=report.events.find(e=>e.id===report.filters.eventId)?.title??"Todos os eventos";if(report.filters.eventId==="orders-export-filters")return event;const lot=report.lots.find(l=>l.id===report.filters.lotId)?.name??"Todos os setores";const method=report.filters.paymentMethod==="PIX"?"Pix":report.filters.paymentMethod==="CREDIT_CARD"?"Cartão de crédito":"Todas as formas";return `${event} | ${lot} | ${method}`}

function header(c:string[],r:Report,page:number,pages:number,filterText?:string){const filters=(filterText??`Filtros: ${filterLabel(r)}`).slice(0,55);c.push(rect(0,H-112,W,112,green),txt(98,H-50,"Relatório de pedidos por evento",25,true,white,45),txt(98,H-76,"Vendas de ingressos - Visão consolidada",13,false,".75 .92 .84 rg",55));vectorIcon(c,61,H-57,"ticket",1.75,".48 .91 .69 RG");c.push(stroke(560,H-94,250,70,".21 .72 .52 RG",1),txt(600,H-47,"Período do relatório",9,false,".75 .92 .84 rg"),txt(600,H-65,`${datePt(r.filters.startDate)} a ${datePt(r.filters.endDate)}`,13,true,white),txt(575,H-84,filters,7.5,false,".75 .92 .84 rg",55),txt(765,H-129,`Página ${page} de ${pages}`,8,true,green,18))}
function kpi(c:string[],x:number,title:string,value:unknown,caption:string,kind:"cart"|"ticket"|"coins"|"percent"){c.push(rect(x,H-230,183,92,white),stroke(x,H-230,183,92),circle(x+31,H-184,22,pale));vectorIcon(c,x+31,H-184,kind);c.push(txt(x+65,H-170,title,10,true,ink,26),txt(x+65,H-194,value,18,true,green,28),txt(x+65,H-213,caption,9,false,muted,24))}
function payment(c:string[],r:Report){const card=r.byMethod.find(x=>x.method==="CREDIT_CARD")?.count??0,pix=r.byMethod.find(x=>x.method==="PIX")?.count??0,total=card+pix,rate=total?card/total:0,cx=365,cy=H-306,rr=58;c.push(rect(28,H-375,786,125,white),stroke(28,H-375,786,125),txt(75,H-290,"Cartão x Pix",15,true,green),txt(75,H-310,"Distribuição das vendas por forma de pagamento",9.5,false,muted,48));vectorIcon(c,51,H-296,"card",1.05);c.push(circle(cx,cy,rr,bright));if(rate>0)c.push(wedge(cx,cy,rr,-Math.PI/2,-Math.PI/2+Math.PI*2*rate,green));c.push(circle(cx,cy,20,white),txt(cx+23,cy-4,`${Math.round(rate*100)}%`,9,true,white),txt(cx-49,cy-4,`${Math.round((1-rate)*100)}%`,9,true,white));c.push(circle(490,H-290,7,green),txt(505,H-294,"Cartão de crédito",10,true),txt(505,H-311,`${card} vendas (${Math.round(rate*100)}%)`,9,false,muted),circle(490,H-334,7,bright),txt(505,H-338,"Pix",10,true),txt(505,H-355,`${pix} vendas (${Math.round((1-rate)*100)}%)`,9,false,muted))}
function tableHeader(c:string[],y:number){c.push(rect(28,y-42,786,42,green));const labels=[[42,"Evento"],[265,"Cidade"],[377,"Ingressos"],[463,"Valor dos ingressos"],[590,"Taxa da bilheteria"],[706,"Juros cartão"]];for(const [x,l] of labels)c.push(txt(Number(x),y-26,l,8,true,white,25));[250,362,450,578,694].forEach(x=>c.push(rule(x,y-42,x,y,".25 .55 .46 RG",.4)))}
function row(c:string[],r:Row,y:number){c.push(rect(28,y-55,786,55,white),stroke(28,y-55,786,55),txt(40,y-23,r.title,9.5,true,green,39),txt(40,y-40,r.venueName,8,false,muted,39),txt(263,y-30,`${r.city}/${r.state}`,8.5,false,ink,20),txt(397,y-30,r.tickets,9,true),txt(466,y-30,formatCurrency(r.ticketNetInCents),8.5,true),txt(598,y-30,formatCurrency(r.serviceFeeInCents),8.5,true),txt(710,y-30,formatCurrency(r.cardInterestInCents),8.5,true))}
function total(c:string[],r:Report,y:number){c.push(rect(28,y-44,786,44,pale),txt(42,y-28,"TOTAL GERAL",12,true,green),txt(397,y-28,r.totals.ticketsIssued,10,true,green),txt(466,y-28,formatCurrency(r.totals.ticketNetInCents),9.5,true,green),txt(598,y-28,formatCurrency(r.totals.serviceFeeInCents),9.5,true,green),txt(710,y-28,formatCurrency(r.totals.cardInterestInCents),9.5,true,green))}
function footer(c:string[],when:Date,page:number,pages:number){c.push(rule(28,58,814,58),txt(62,37,"Relatório gerado automaticamente pelo sistema de vendas de ingressos.",8,false,muted,80),txt(62,24,"Em caso de dúvidas, entre em contato com a equipe.",8,false,muted,70),txt(508,37,"Gerado em",8,false,muted),txt(508,24,issued(when),8,true,muted),txt(690,30,`Página ${page} de ${pages}`,8,true,green));vectorIcon(c,43,32,"ticket",.75,".08 .72 .45 RG")}
function pdf(pages:string[]){const o:string[]=["<< /Type /Catalog /Pages 2 0 R >>","","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>"],nums:number[]=[];for(const content of pages){const n=o.length+1;o.push(`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);nums.push(o.length+1);o.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${n} 0 R >>`)}o[1]=`<< /Type /Pages /Kids [${nums.map(n=>`${n} 0 R`).join(" ")}] /Count ${nums.length} >>`;let out="%PDF-1.4\n";const offsets=[0];o.forEach((v,i)=>{offsets.push(Buffer.byteLength(out));out+=`${i+1} 0 obj\n${v}\nendobj\n`});const xr=Buffer.byteLength(out);out+=`xref\n0 ${o.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>`${String(x).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${o.length+1} /Root 1 0 R >>\nstartxref\n${xr}\n%%EOF`;return Buffer.from(out)}

export function buildFinanceEventsPdf(report:Report){const when=new Date(),chunks:Row[][]=[];for(let i=0;i<report.byEvent.length;i+=5)chunks.push(report.byEvent.slice(i,i+5));if(!chunks.length)chunks.push([]);return pdf(chunks.map((rows,index)=>{const c:string[]=[];header(c,report,index+1,chunks.length);let y;if(index===0){kpi(c,28,"Pedidos",report.totals.paidOrders,"no filtro","cart");kpi(c,229,"Ingressos",report.totals.ticketsIssued,"vendidos","ticket");kpi(c,430,"Valor dos ingressos",formatCurrency(report.totals.ticketNetInCents),"sem taxas","coins");kpi(c,631,"Taxa da bilheteria",formatCurrency(report.totals.serviceFeeInCents),"taxa paga","percent");payment(c,report);c.push(txt(42,H-411,"Detalhamento por evento",16,true,ink),txt(42,H-428,"Confira abaixo o desempenho de cada evento no período selecionado.",9,false,muted));y=H-448}else{c.push(txt(42,H-154,"Detalhamento por evento - continuação",15,true,ink));y=H-176}tableHeader(c,y);let rowY=y-42;rows.forEach(item=>{row(c,item,rowY);rowY-=55});if(index===chunks.length-1)total(c,report,rowY-8);footer(c,when,index+1,chunks.length);return c.join("\n") }))}

export async function GET(request:Request){const admin=await requirePermission("FINANCE"),url=new URL(request.url);const report=await getFinanceReport({eventId:url.searchParams.get("eventId")||undefined,lotId:url.searchParams.get("lotId")||undefined,paymentMethod:url.searchParams.get("paymentMethod")||undefined,startDate:url.searchParams.get("startDate")||undefined,endDate:url.searchParams.get("endDate")||undefined},admin.organizationId,getAdminAllowedEventIds(admin));return new NextResponse(buildFinanceEventsPdf(report),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="relatorio-pedidos-por-evento-${new Date().toISOString().slice(0,10)}.pdf"`}})}
