import { describe, expect, it } from "vitest";
import { getAdmissionCount } from "@/features/tickets/admission-count";

describe("admission count", () => {
  it("counts every QR code generated by single and double tickets", () => {
    expect(
      getAdmissionCount([
        { quantity: 3, admissionsPerUnit: 1 },
        { quantity: 2, admissionsPerUnit: 2 }
      ])
    ).toBe(7);
  });

  it("uses one admission for legacy items without the snapshot", () => {
    expect(getAdmissionCount([{ quantity: 2 }])).toBe(2);
  });
});
